version: '3'
services:
  sitespeed:
    container_name: sitespeed
    image: sitespeedio/sitespeed.io
    command: ["/mnt/urls.txt", "--config", "/mnt/config.json"]
    shm_size: 1g
    volumes:
      - ./config.json:/mnt/config.json:ro
      - ./urls.txt:/mnt/urls.txt:ro
      - ./data/sitespeed-result/:/sitespeed.io/sitespeed-result
  grafana:
    image: grafana/grafana:8.2.3
    hostname: grafana
    depends_on:
      - graphite
    links:
      - graphite
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=hdeAga76VG6ga7plZ1
      - GF_SECURITY_ADMIN_USER=sitespeedio
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana:/var/lib/grafana
    restart: always
  graphite:
    image: sitespeedio/graphite:1.1.7-9
    hostname: graphite
    ports:
      - "2003:2003"
      - "8080:80"
    # restart: always
    volumes:
      - whisper:/opt/graphite/storage/whisper
  grafana-setup:
    image: sitespeedio/grafana-bootstrap:20.4.0
    links:
      - grafana
    environment:
      - GF_PASSWORD=hdeAga76VG6ga7plZ1
      - GF_USER=sitespeedio
volumes:
    grafana:
    whisper: