version: '3'
networks:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/29
services:
  sitespeed:
    networks:
      private:
        ipv4_address: 10.1.1.2
        aliases:
         - sitespeed
    container_name: sitespeed
    image: sitespeedio/sitespeed.io
    command: ["/mnt/urls.txt", "--config", "/mnt/config.json"]
    shm_size: 1g
    volumes:
      - ./config.json:/mnt/config.json:ro
      - ./urls.txt:/mnt/urls.txt:ro
      - ./data/sitespeed-result/:/sitespeed.io/sitespeed-result
  # grafana:
  #   networks:
  #     private:
  #       ipv4_address: 10.1.1.4
  #       aliases:
  #        - grafana
  #   container_name: grafana
  #   image: grafana/grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./data/grafana:/var/lib/grafana:rw
  #   depends_on:
  #     - statsd
  #   environment:
  #     GF_SECURITY_ADMIN_USER: admin
  #     GF_SECURITY_ADMIN_PASSWORD: admin
  #     GF_AUTH_ANONYMOUS_ENABLED: "true"
  #     GF_USERS_ALLOW_SIGN_UP: "false"
  #     GF_USERS_ALLOW_ORG_CREATE: "false"
  # statsd:
  #   networks:
  #     private:
  #       ipv4_address: 10.1.1.5
  #       aliases:
  #        - statsd
  #   container_name: statsd
  #   image: graphiteapp/graphite-statsd
  #   ports:
  #     - "80:80"
  #     - "2003-2004:2003-2004"
  #     - "2023-2024:2023-2024"
  #     - "8125:8125/udp"
  #     - "8126:8126"
  #   # restart: always
  #   volumes:
  #     # - ./data/whisper:/opt/graphite/storage/whisper:rw
  #     - ./data/graphite:/opt/graphite/storage:rw
  # grafana-setup:
  #   image: sitespeedio/grafana-bootstrap:8.8.0
  #   environment:
  #     GF_PASSWORD: admin
  #     GF_USER: admin